inherit_mode:
  merge:
    - Exclude

require:
  - standard

plugins:
  - rubocop-performance
  - rubocop-rails
  - standard-custom
  - standard-performance

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml
  standard-rails: config/base.yml

inherit_from:
  - .rubocop_todo.yml
  - .rubocop_strict.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2