/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconPhCaretRightFill: typeof import('~icons/ph/caret-right-fill.jsx')['default']
}
